# Generated by Django 4.0.6 on 2022-07-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('Premiere', models.DateTimeField()),
            ],
        ),
    ]
